### ISSUE TITLE
gps .conf files not building

### ISSUE THREAD

**Issue by Howarddj** [Professor-Berni/android_device_sony_kitakami-common#2]
latest gps commit is not recognizing *.conf files located in gps/etc.
build process is looking for them in /gps.
causes build to fail.

**Comment by Professor-Berni** [comment]
That can be built without any problems here:

- Install: out/target/product/suzuran/system/etc/flp.conf
- Install: out/target/product/suzuran/system/etc/gps.conf
- Install: out/target/product/suzuran/system/etc/izat.conf
- Install: out/target/product/suzuran/system/etc/sap.conf

Dunno what's wrong at your side...

**Comment by Howarddj** [comment]
understood, its probably a problem with what im trying to build. trees obviously work properly for suzuran so ill close the issue.
ive been trying to build for another kitakami device (karin z4 tablet) and trying to bring up trees from Lineage to arrowOS so im not suprised it isnt working.
thanks for the reply anyway
